### ISSUE TITLE
Don't depend on npm

### ISSUE THREAD

**Issue by sindresorhus** [kevva/npm-conf#1]
npm is a super heavy dependency. Would be better to just reimplement the npm config algorithm. It doesn't look that hard.

Basically:

- Use https://github.com/dominictarr/config-chain
- Include its defaults from https://github.com/npm/npm/blob/6f09d6d2d915cdccfee6f423d7f14135be89e9f9/lib/config/defaults.js (Could probably be scraped with a simple script at publish time)
- This logic: https://github.com/npm/npm/blob/6f09d6d2d915cdccfee6f423d7f14135be89e9f9/lib/config/core.js#L101-L222
- This function: https://github.com/npm/npm/blob/6f09d6d2d915cdccfee6f423d7f14135be89e9f9/lib/config/core.js#L409

We only care about reading the config. Not the other 1000 things the config handling in npm is doing.

This way we could also make it synchronous, so simpler interface and faster.

**Comment by shinnn** [comment]
> Would be better to just reimplement the npm config algorithm.

Another option: load `./lib/config/core.js` from the npm CLI you've installed.

[npm-cli-dir](https://github.com/shinnn/npm-cli-dir) resolves the path where the `npm` CLI exists,

```js
const npmCliDir = require('npm-cli-dir');

npmCliDir().then(dir => {
  console.log(dir); //=> /usr/local/lib/node_modules/npm
});
```

and you can easily import `./lib/config/core.js` relative to it:

```js
'use strict';
const path = require('path');
const npmCliDir = require('npm-cli-dir');
const pify = require('pify');

module.exports = () => npmCliDir()
  .then(dir => require(path.join(dir, 'lib/config/core')))
  .then(npmconf => pify(npmconf.load)());
```

__pros__

* Smaller bundle size than huge `npm`
* No duplicate work like https://github.com/kevva/npm-conf/commit/447e119ab9841d8b92fe1e0dd75672658e65fae9

__cons__

* A bit fragile. If npm changes its directory structure in the future, this approach does't work correctly. The npm team is currently enough [sensitive about moving or deleting files in the CLI](https://github.com/npm/npm/pull/12096#issuecomment-203670099) though.

**Comment by sindresorhus** [comment]
> A bit fragile.

Very fragile I would say.

**Comment by kevva** [comment]
I have my `npm` installed in `/Users/kevva/.npm-packages/bin/npm` which wouldn't work using that method.

**Comment by shinnn** [comment]
> Very fragile I would say.

@sindresorhus I understand your concern 😅 https://github.com/kevva/npm-conf/issues/1#issuecomment-304066545 was just FYI.

> I have my `npm` installed in `/Users/kevva/.npm-packages/bin/npm` which wouldn't work using that method.

Hmm, `npm-cli-dir` did't resolve it to `/Users/kevva/.npm-packages/lib/node_modules/npm`? That's unintended.

**Comment by kevva** [comment]
Never mind. I'm just being stupid :).

**Comment by sindresorhus** [comment]
> My brain has taken toll reading through the npm code all day.

Been there, like literally.
