### ISSUE TITLE
Maybe a bug?

### ISSUE THREAD

**Issue by tbenade** [kevva/npm-conf#3]
Hi, thought you may be interested in this issue over in the serverless repo.

https://github.com/serverless/serverless/issues/3978

**Comment by kevva** [comment]
@tbenade, could you guys try again now?

**Comment by huysamen** [comment]
Yeah, seems fixed.  Cudos on the response time :)

**Comment by kevva** [comment]
:+1:

**Comment by tbenade** [comment]
👍
